
export const LOADING = 'LOADING'
export const FAILED = 'FAILED'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const AGENT_LOADING = 'AGENT_LOADING'
export const READY_FAILED = 'READY_FAILED'
export const READY_SUCCESS = 'READY_SUCCESS'
export const NOTREADY_FAILED = 'NOTREADY_FAILED'
export const NOTREADY_SUCCESS = 'NOTREADY_SUCCESS'
export const ISREADY_SUCCESS = 'ISREADY_SUCCESS'
export const ISREADY_FAILED = 'ISREADY_FAILED'
export const GETCHANNEL_SUCCESS = 'GETCHANNEL_SUCCESS'
export const GETCHANNEL_FAILED = 'GETCHANNEL_FAILED'
export const SUBMITWORKCODE_SUCCESS = 'SUBMITWORKCODE_SUCCESS'
export const SUBMITWORKCODE_FAILED = 'SUBMITWORKCODE_FAILED'

export const QLOGIN_SUCCESS = 'QLOGIN_SUCCESS'
export const QLOGIN_FAILED = 'QLOGIN_FAILED'
export const QLOGOUT_SUCCESS = 'QLOGOUT_SUCCESS'
export const QLOGOUT_FAILED = 'QLOGOUT_FAILED'

export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILED = 'USER_FAILED'

export const SYSTEM_LOADING = 'SYSTEM_LOADING'
export const SYSTEM_SUCCESS = 'SYSTEM_SUCCESS'
export const SYSTEM_FAILED = 'SYSTEM_FAILED'

export const REASON_SUCCESS = 'REASON_SUCCESS'
export const REASON_FAILED = 'REASON_SUCCESS'

export const STATUS_LOADING = 'STATUS_LOADING'
export const STATUS_SUCCESS = 'STATUS_SUCCESS'
export const STATUS_FAILED = 'STATUS_FAILED'

export const WORKCODE_LOADING = 'WORKCODE_LOADING'
export const WORKCODE_SUCCESS = 'WORKCODE_SUCCESS'
export const WORKCODE_FAILED = 'WORKCODE_FAILED'

export const GETWORKCODE_LOADING = 'GETWORKCODE_LOADING'
export const GETWORKCODE_SUCCESS = 'GETWORKCODE_SUCCESS'
export const GETWORKCODE_FAILED = 'GETWORKCODE_FAILED'

export const OUTBOUND_WORKCODE_SUCCESS = 'OUTBOUND_WORKCOD_SUCCESS'
export const OUTBOUND_WORKCODE_FAILED = 'OUTBOUND_WORKCODE_FAILED'